language: node_js
node_js:
  - "8"
script: npm run build
deploy:
  provider: pages
  local-dir: www
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  committer-from-gh: true
  on:
    branch: master