language: node_js
branches:
  only:
    - "master"
node_js:
  - "12"
script: npm run lint && npm run build
deploy:
  provider: pages
  local-dir: www
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  committer-from-gh: true
  on:
    branch: master
