name: Lint and Build

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: pnpm/action-setup@v3

      - name: Lint and Build
        run: |
          pnpm install
          pnpm lint
          pnpm build
