name: Lint and Build

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v4
        with:
          node-version: 14.x

      - name: Lint and Build
        run: |
          npm ci
          npm run lint
          npm run build
